service: ping-pong-graphql-api
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    ITEM_TABLE: ping-pong-scores-dev # table name
  iamRoleStatements:
    - Effect: Allow # allow the Lambda to Get and Put Items of this table
      Action:
        - dynamodb:GetItem 
        - dynamodb:PutItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/ping-pong-scores-dev'

resources:
  Resources:
    ItemsTable: # define the table
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: itemId
            AttributeType: S
        KeySchema:
          - AttributeName: itemId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'ping-pong-scores-dev'
functions:
  graphql:
    handler: src/apollo-server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
plugins:
  - serverless-webpack
  - serverless-offline
custom:
  webpack:
    includeModules: true